<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>prg</string>
		<string>ch</string>
	</array>
	<key>name</key>
	<string>Harbour</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>números</string>
			<key>match</key>
			<string>\b(((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?))</string>
			<key>name</key>
			<string>constant.numeric.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cadenas comillas simples</string>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cadenas comillas dobles</string>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.quoted.double.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>sentencias de control</string>
			<key>match</key>
			<string>(?i)\b(?:do|case|endcase|otherwise|switch|if|else|endif|while|end|enddo|exit|static function|function|return|for|next|include|ifdef|stdout|ifndef)\b</string>
			<key>name</key>
			<string>keyword.control.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>sentencias de control</string>
			<key>match</key>
			<string>(?i)\b(?:catch|finally|try|throw)\b</string>
			<key>name</key>
			<string>keyword.control.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operadores</string>
			<key>match</key>
			<string>(?i)\b(?:and|or|not|!)\b</string>
			<key>name</key>
			<string>keyword.operator.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>declaraciones</string>
			<key>match</key>
			<string>(?i)\b(?:local|default|field|static|public|static|external|request|private)\b</string>
			<key>name</key>
			<string>storage.type.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>in-line comment with // or *</string>
			<key>match</key>
			<string>((//|\*).*)</string>
			<key>name</key>
			<string>comment.strings.harbour</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*/\*.*)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.strings.harbour</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>multi-line comments</string>
			<key>end</key>
			<string>^(\s*\*/\s*)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.strings.harbour</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.strings.harbour</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones A</string>
			<key>match</key>
			<string>(?i)\b(?:AADD|ABS|ACHOICE|ACLONE|ACOPY|ADEL|ADIR|AEVAL|AFIELDS|AFILL|AINS|ALERT|ALIAS|ALLTRIM|ARRAY|ASC|ASCAN|ASIZE|ASORT|AT|ATAIL|ASCIISum|AscPos|ASin|ASizeAlloc|AtAdjust|ATan|ACos|ATn2|AtNum|AtRepl|AtSkipStrings|AtToken|)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones B</string>
			<key>match</key>
			<string>(?i)\b(?:BIN2I|BIN2L|BIN2U|BIN2W|BOF|BREAK|BROWSE)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones C</string>
			<key>match</key>
			<string>(?i)\b(?:CDOW|CHR|CLIPINIT|CMONTH|COL|CTOD|CURDIR)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones D</string>
			<key>match</key>
			<string>(?i)\b(?:DATE|DAY|DAYS|DBAPPEND|DBCLEARFILTER|DBCLOSEALL|DBCLOSEAREA|DBCOMMIT|DBCOMMITALL|DBCREATE|DBDELETE|DBEDIT|DBEVAL|DBF|DBFILTER|DBGOBOTTOM|DBGOTO|DBGOTOP|DBRECALL|DBRLOCK|DBRLOCKLIST|DBRUNLOCK|DBSEEK|DBSELECTAREA|DBSETDRIVER|DBSETFILTER|DBSKIP|DBSTRUCT|DBUNLOCK|DBUNLOCKALL|DBUSEAREA|DELETED|DESCEND|DEVOUTPICT|DIRCHANGE|DIRREMOVE|DISKSPACE|DOW|DTOC|DTOS|dbSkipper|Directory)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones E</string>
			<key>match</key>
			<string>(?i)\b(?:ELAPTIME|EMPTY|EOF|ERRORSYS|EVAL|EXP|FCLOSE|FCOUNT|FCREATE|FERASE|FERROR|FIELDBLOCK|FIELDGET|FIELDNAME|FIELDPOS|FIELDPUT|FIELDWBLOCK|FILE|FLOCK|FOPEN|FOUND|FREAD|FREADSTR|FRENAME|FSEEK|FWRITE)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones F</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones G</string>
			<key>match</key>
			<string>(?i)\b(?:GETENV)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones H</string>
			<key>match</key>
			<string>(?i)\b(?:HARDCR|HB_ANSITOOEM|HB_DISKSPACE|HB_FEOF|HB_KEYPUT|HB_LANGNAME|HB_LANGSELECT|HB_OEMTOANSI|HB_OSNEWLINE|HB_PVALUE|HB_SetKeyCheck|HB_SetKeyGet|HB_SETKEYSAVE|HB_VALTOSTR|HEADER|hb_ColorIndex)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones I</string>
			<key>match</key>
			<string>(?i)\b(?:I2BIN|INDEXEXT|INDEXKEY|INDEXORD|INKEY|INT|ISAFFIRM|ISALPHA|ISDIGIT|ISDISK|ISLOWER|ISNEGATIVE|ISUPPER)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones J</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones K</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones L</string>
			<key>match</key>
			<string>(?i)\b(?:L2BIN|LASTKEY|LASTREC|LEFT|LOG|LOWER|LTRIM|LUPDATE)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones M</string>
			<key>match</key>
			<string>(?i)\b(?:MAKEDIR|MAX|MAXCOL|MAXROW|MCOL|MEMOEDIT|MEMOTRAN|MEMOWRIT|MEMVARBLOCK|MIN|MOD|MONTH|MROW)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones N</string>
			<key>match</key>
			<string>(?i)\b(?:NATIONMSG|NETERR|NEXTKEY)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones O</string>
			<key>match</key>
			<string>(?i)\b(?:ORDBAGEXT|ORDBAGNAME|ORDCONDSET|ORDCREATE|ORDDESTROY|ORDFOR|ORDKEY|ORDLISTADD|ORDLISTCLEAR|ORDLISTREBUILD|ORDNAME|ORDNUMBER|ORDSETFOCUS|OS|OUTERR|OUTSTD)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones P</string>
			<key>match</key>
			<string>(?i)\b(?:PADC|PADL|PADR|PCOUNT|PROCFILE|PROCLINE|PROCNAME)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones Q</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones R</string>
			<key>match</key>
			<string>(?i)\b(?:RAT|RDDLIST|RDDNAME|RDDSETDEFAULT|READKEY|READVAR|RECCOUNT|RECNO|RECSIZE|REPLICATE|RIGHT|RLOCK|ROUND|ROW|RTRIM)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones S</string>
			<key>match</key>
			<string>(?i)\b(?:SECONDS|SECS|SELECT|SET|SETKEY|SETMODE|SETTYPEAHEAD|SPACE|SQRT|STR|STRTRAN|STRZERO|SUBSTR)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones T</string>
			<key>match</key>
			<string>(?i)\b(?:TBrowseDB|TBROWSENew|TClass|TIME|TONE|TRANSFORM|TRIM|TYPE)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones U</string>
			<key>match</key>
			<string>(?i)\b(?:U2BIN|UPPER|USED)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones V</string>
			<key>match</key>
			<string>(?i)\b(?:VAL|VALTYPE|VERSION)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones W</string>
			<key>match</key>
			<string>(?i)\b(?:W2BIN|WORD)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones X</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones Y</string>
			<key>match</key>
			<string>(?i)\b(?:YEAR)\b</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>funciones Z</string>
			<key>match</key>
			<string>(?i)\b(?:)</string>
			<key>name</key>
			<string>support.function.basic.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Definition class</string>
			<key>match</key>
			<string>(?i)\b(?:class|classdata|data|method|message|var|endclass|onerror|error handler)</string>
			<key>name</key>
			<string>support.class.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Definicion de constantes caracter</string>
			<key>match</key>
			<string>(?i)\b(?:include|define|ifdef)</string>
			<key>name</key>
			<string>support.constant.character.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Definicion de constantes logicas</string>
			<key>match</key>
			<string>(?i)\b(?:true|false|nil)</string>
			<key>name</key>
			<string>support.constant.language.harbour</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean</string>
			<key>match</key>
			<string>(?i)(\.(T|F)\.)</string>
			<key>name</key>
			<string>constant.numeric.harbour</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.harbour</string>
	<key>uuid</key>
	<string>56571807-d94d-4805-bbfc-87d347d189e4</string>
</dict>
</plist>
